/**
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

#ifndef IIS2DULPX_ACTIVITY_RECOGNITION_FOR_WRIST_H
#define IIS2DULPX_ACTIVITY_RECOGNITION_FOR_WRIST_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#ifndef MEMS_UCF_EXT_SHARED_TYPES
#define MEMS_UCF_EXT_SHARED_TYPES

/*
 * UCF extended format supports the following commands:
 * - MEMS_UCF_OP_READ: read the register at the location specified by the
 *   "address" field ("data" field is ignored
 * - MEMS_UCF_OP_WRITE: write the value specified by the "data" field at the
 *   location specified by the "address" field
 * - MEMS_UCF_OP_DELAY: wait the number of milliseconds specified by the "data"
 *   field ("address" field is ignored)
 * - MEMS_UCF_OP_POLL_SET: poll the register at the location specified by the
 *   "address" field until all the bits identified by the mask specified by the
 *   "data" field are set to 1
 * - MEMS_UCF_OP_POLL_RESET: poll the register at the location specified by the
 *   "address" field until all the bits identified by the mask specified by the
 *   "data" field are reset to 0
 */

#define MEMS_UCF_OP_READ       0
#define MEMS_UCF_OP_WRITE      1
#define MEMS_UCF_OP_DELAY      2
#define MEMS_UCF_OP_POLL_SET   3
#define MEMS_UCF_OP_POLL_RESET 4

typedef struct {
  uint8_t op;
  uint8_t address;
  uint8_t data;
} ucf_line_ext_t;

#endif /* MEMS_UCF_EXT_SHARED_TYPES */

/** Configuration array generated from Unico Tool **/
static const ucf_line_ext_t iis2dulpx_activity_recognition_for_wrist[] = {
  { .op = MEMS_UCF_OP_WRITE, .address = 0x13, .data = 0x10 },
  { .op = MEMS_UCF_OP_DELAY, .address = 0, .data = 5 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x14, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3F, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x04, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x05, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x17, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0xB8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x54 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x60 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x32 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0xC8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xDC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x88 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0xDC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x07 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x46 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xBE },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x35 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x02 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x02 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x03 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x03 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x04 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x04 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x1F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x7C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3F, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3F, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x17, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x88 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x45 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x83 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x60 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x88 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x90 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x29 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x87 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x08 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x8A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE6 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x94 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xDB },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x56 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x55 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC1 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA4 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA7 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x60 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x88 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x1F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x87 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x55 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x16 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x82 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x34 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC7 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x45 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA3 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xB9 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x51 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xCA },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xBE },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x38 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xAA },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xFB },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x30 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x1A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x81 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x60 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x94 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x59 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x57 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xB4 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x6B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x1E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x84 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x34 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA1 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x72 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE4 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x21 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x72 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE1 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xAB },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x28 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x81 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x27 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x8A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x25 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x87 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF3 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x57 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x24 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x82 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x34 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xEA },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x1B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xED },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x58 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x61 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE9 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x68 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x56 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x92 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xAA },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA7 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x44 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x84 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x36 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x8A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x48 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x32 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x89 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x31 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF1 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xDD },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x38 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xAA },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x2F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC1 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xB7 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE4 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x04 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x31 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xCA },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA6 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x60 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE4 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x57 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x41 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3A },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x88 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF8 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x81 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xCC },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xD3 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x56 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA2 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x49 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE9 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x14 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE6 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC3 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3F },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x3D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x81 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x18 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE6 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x42 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x87 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xED },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x42 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x84 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x48 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x84 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE9 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA7 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x44 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x84 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE4 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF5 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x39 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x38 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xCA },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x9D },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x43 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA4 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x40 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x49 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA9 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x0B },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4E },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x84 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xE0 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3F, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x17, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x04, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x05, .data = 0x10 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3F, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x1F, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3F, .data = 0x80 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x0D, .data = 0x01 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3A, .data = 0x11 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x3F, .data = 0x00 },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x14, .data = 0x62 }
};

#ifdef __cplusplus
}
#endif

#endif /* IIS2DULPX_ACTIVITY_RECOGNITION_FOR_WRIST_H */

